classDiagram
    class ExitStatus {
    }
    class HTTPieHelpFormatter {
      +__init__()
      +_split_lines()
    }
    class BaseConfigDict {
      +__getattr__()
      +_get_path()
      +path()
      +is_new()
      +load()
      +save()
      +delete()
    }
    class Config {
      +__init__()
      +_get_path()
    }
    class Environment {
      +__init__()
      +config()
    }
    class ContentRangeError {
    }
    class Download {
      +__init__()
      +pre_request()
      +start()
      +finish()
      +failed()
      +interrupted()
      +chunk_downloaded()
    }
    class Status {
      +__init__()
      +started()
      +chunk_downloaded()
      +has_finished()
      +finished()
    }
    class ProgressReporterThread {
      +__init__()
      +stop()
      +run()
      +report_speed()
      +sum_up()
    }
    class Parser {
      +__init__()
      +parse_args()
      +_print_message()
      +_setup_standard_streams()
      +_apply_config()
      +_process_auth()
      +_apply_no_options()
      +_body_from_file()
      +_guess_method()
      +_parse_items()
      +_process_output_options()
      +_process_pretty_options()
      +_validate_download_options()
    }
    class ParseError {
    }
    class KeyValue {
      +__init__()
      +__eq__()
    }
    class SessionNameValidator {
      +__init__()
      +__call__()
    }
    class KeyValueArgType {
      +__init__()
      +__call__()
    }
    class AuthCredentials {
      +_getpass()
      +has_password()
      +prompt_password()
    }
    class AuthCredentialsArgType {
      +__call__()
    }
    class ParamDict {
      +__setitem__()
    }
    class HTTPMessage {
      +__init__()
      +iter_body()
      +iter_lines()
      +headers()
      +encoding()
      +body()
      +content_type()
    }
    class HTTPResponse {
      +iter_body()
      +iter_lines()
      +headers()
      +encoding()
      +body()
    }
    class HTTPRequest {
      +iter_body()
      +iter_lines()
      +headers()
      +encoding()
      +body()
    }
    class ColorFormatter {
      +__init__()
      +format_headers()
      +format_body()
      +get_lexer()
    }
    class HTTPLexer {
    }
    class Solarized256Style {
    }
    class HeadersFormatter {
      +format_headers()
    }
    class JSONFormatter {
      +format_body()
    }
    class XMLFormatter {
      +format_body()
    }
    class Conversion {
      +get_converter()
    }
    class Formatting {
      +__init__()
      +format_headers()
      +format_body()
    }
    class BinarySuppressedError {
    }
    class BaseStream {
      +__init__()
      +get_headers()
      +iter_body()
      +__iter__()
    }
    class RawStream {
      +__init__()
      +iter_body()
    }
    class EncodedStream {
      +__init__()
      +iter_body()
    }
    class PrettyStream {
      +__init__()
      +get_headers()
      +iter_body()
      +process_body()
    }
    class BufferedPrettyStream {
      +iter_body()
    }
    class BasePlugin {
    }
    class AuthPlugin {
      +get_auth()
    }
    class ConverterPlugin {
      +__init__()
      +convert()
      +supports()
    }
    class FormatterPlugin {
      +__init__()
      +format_headers()
      +format_body()
    }
    class BuiltinAuthPlugin {
    }
    class HTTPBasicAuth {
      +__call__()
      +make_header()
    }
    class BasicAuthPlugin {
      +get_auth()
    }
    class DigestAuthPlugin {
      +get_auth()
    }
    class PluginManager {
      +__init__()
      +__iter__()
      +register()
      +load_installed_plugins()
      +get_auth_plugins()
      +get_auth_plugin_mapping()
      +get_auth_plugin()
      +get_formatters()
      +get_formatters_grouped()
      +get_converters()
    }
    class Session {
      +__init__()
      +_get_path()
      +update_headers()
      +headers()
      +cookies()
      +cookies()
      +auth()
      +auth()
    }
    BaseConfigDict <|-- Config
    KeyValue <|-- AuthCredentials
    KeyValueArgType <|-- AuthCredentialsArgType
    HTTPMessage <|-- HTTPResponse
    HTTPMessage <|-- HTTPRequest
    FormatterPlugin <|-- ColorFormatter
    FormatterPlugin <|-- HeadersFormatter
    FormatterPlugin <|-- JSONFormatter
    FormatterPlugin <|-- XMLFormatter
    BaseStream <|-- RawStream
    BaseStream <|-- EncodedStream
    EncodedStream <|-- PrettyStream
    PrettyStream <|-- BufferedPrettyStream
    BasePlugin <|-- AuthPlugin
    AuthPlugin <|-- BuiltinAuthPlugin
    HTTPBasicAuth <|-- HTTPBasicAuth
    BuiltinAuthPlugin <|-- BasicAuthPlugin
    BuiltinAuthPlugin <|-- DigestAuthPlugin
    BaseConfigDict <|-- Session
    Environment *-- Config
    Download *-- HTTPResponse
    Download *-- ProgressReporterThread
    Download *-- RawStream
    Download *-- Status
    Parser *-- AuthCredentials
    Parser *-- KeyValueArgType
    Parser *-- ParamDict
    ColorFormatter *-- HTTPLexer
    Formatting *-- Environment
    EncodedStream *-- BinarySuppressedError
    EncodedStream *-- Environment
    PrettyStream *-- BinarySuppressedError
    BufferedPrettyStream *-- BinarySuppressedError
    BasicAuthPlugin *-- HTTPBasicAuth
