"""Generate the PRIMARY-target OOP class diagram (EX04 §5.2) for the httpie / BugsInPy target.

httpie (a soarsmu/BugsInPy project — PDF-listed §2) is class-bearing, so the OOP class-diagram
requirement is met ON THE INVESTIGATED TARGET (not a procedural one): real inheritance
(HTTPMessage <|-- HTTPRequest/HTTPResponse, FormatterPlugin <|-- 4 formatters, BaseStream <|-- ...)
and composition, auto-extracted by the same AST pipeline (sdk.extract_class_schema). The bug under
investigation (BugsInPy httpie bug 4) lives in the HTTPRequest class shown here.

    git clone https://github.com/httpie/cli runs/httpie-bug
    git -C runs/httpie-bug checkout 8c892edd4fe700a7ca5cc733dcb4817831d253e2
    uv run python scripts/gen_httpie_oop.py
"""

from collections import Counter
from pathlib import Path

from archlens.sdk.sdk import ArchLensSDK

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "runs" / "httpie-bug" / "httpie"
OUT = ROOT / "deliverables" / "CLASS_SCHEMA.md"
OUT_MMD = ROOT / "docs" / "diagrams" / "httpie_classes.mmd"


def _hierarchies(relations) -> list[str]:
    inh = {(r.source, r.target) for r in relations if r.kind == "inheritance"}
    picks = [("HTTPMessage", "HTTPRequest"), ("HTTPMessage", "HTTPResponse"),
             ("FormatterPlugin", "ColorFormatter"), ("FormatterPlugin", "JSONFormatter"),
             ("BaseStream", "RawStream"), ("BaseConfigDict", "Config")]
    return [f"- `{base}` <|-- `{sub}`" for base, sub in picks if (base, sub) in inh]


def main() -> int:
    if not SRC.is_dir():
        raise SystemExit(f"clone+checkout the buggy httpie first (see module docstring); missing {SRC}")
    schema = ArchLensSDK().extract_class_schema(SRC)
    kinds = Counter(r.kind for r in schema["relations"])
    doc = [
        "# OOP Class Schema - httpie (EX04 §5.2, primary class-bearing target)",
        "",
        "Version: 1.00 | Course: AI Agent Orchestration - HW4 (EX04)",
        "",
        "> **Provenance.** Auto-generated by `scripts/gen_httpie_oop.py` via `sdk.extract_class_schema` "
        "(pure-AST `extract_classes` + `class_relations` + `render_class_diagram`; no LLM, no tokens) "
        "over the buggy httpie checkout at `runs/httpie-bug/httpie` (soarsmu/BugsInPy bug 4, commit "
        "`8c892edd`). httpie is a PDF-listed BugsInPy project (§2) and is class-bearing, so the OOP "
        "class-diagram requirement is satisfied ON THE INVESTIGATED TARGET. The bug under "
        "investigation lives in the `HTTPRequest` class shown below.",
        "",
        "## Summary",
        "",
        f"- Classes extracted: **{len(schema['classes'])}**",
        f"- Inheritance edges (`<|--`): **{kinds.get('inheritance', 0)}**",
        f"- Composition edges (`*--`): **{kinds.get('composition', 0)}**",
        "",
        "Representative inheritance hierarchies (verified in the extracted relations):",
        *_hierarchies(schema["relations"]),
        "",
        "## Class Diagram (full, auto-extracted)",
        "",
        schema["diagram"],
        "",
    ]
    OUT.write_text("\n".join(doc) + "\n", encoding="utf-8")
    raw_mmd = schema["diagram"].removeprefix("```mermaid\n").removesuffix("```").rstrip() + "\n"
    OUT_MMD.write_text(raw_mmd, encoding="utf-8")
    print(f"wrote {OUT} + {OUT_MMD} ({len(schema['classes'])} classes, "
          f"{kinds.get('inheritance', 0)} inheritance, {kinds.get('composition', 0)} composition)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
