"""Generate deliverables/CLASS_SCHEMA_requests.md — a REAL OOP class diagram (EX04 §5.2).

The primary debugging target (andela/buggy-python) is procedural, so its class diagram is honestly
empty. To satisfy the §5.2 OOP requirement (classes + inheritance + composition + encapsulation), we
also reverse-engineer the class-bearing secondary target psf/requests (the project's configured
fallback repo) with the SAME AST extraction pipeline — `sdk.extract_class_schema` over
`extract_classes`/`class_relations`/`render_class_diagram`. Extraction is pure AST (no LLM, no tokens).

Run: clone the target then generate:
    git clone --depth 1 https://github.com/psf/requests runs/requests
    uv run python scripts/gen_requests_oop.py
"""

from collections import Counter
from pathlib import Path

from archlens.sdk.sdk import ArchLensSDK

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "runs" / "requests" / "src" / "requests"
OUT = ROOT / "deliverables" / "CLASS_SCHEMA_requests.md"


def _hierarchies(relations) -> list[str]:
    """A few representative inheritance chains base -> subclass for the summary."""
    inh = [(r.source, r.target) for r in relations if r.kind == "inheritance"]
    picks = [("BaseAdapter", "HTTPAdapter"), ("AuthBase", "HTTPBasicAuth"),
             ("HTTPBasicAuth", "HTTPProxyAuth"), ("RequestException", "HTTPError"),
             ("InvalidJSONError", "JSONDecodeError"), ("CookieJar", "RequestsCookieJar")]
    return [f"- `{base}` <|-- `{sub}`" for base, sub in picks if (base, sub) in inh]


def main() -> int:
    if not SRC.is_dir():
        raise SystemExit(f"clone the target first: git clone --depth 1 "
                         f"https://github.com/psf/requests runs/requests  (missing {SRC})")
    schema = ArchLensSDK().extract_class_schema(SRC)
    kinds = Counter(r.kind for r in schema["relations"])
    doc = [
        "# OOP Class Schema - psf/requests (EX04 §5.2 secondary, class-bearing target)",
        "",
        "Version: 1.00 | Course: AI Agent Orchestration - HW4 (EX04)",
        "",
        "> **Provenance.** Auto-generated by `scripts/gen_requests_oop.py` via "
        "`sdk.extract_class_schema` (pure-AST `extract_classes` + `class_relations` + "
        "`render_class_diagram`; no LLM, no tokens) over a `psf/requests` clone at "
        "`runs/requests/src/requests`. The primary debugging target `andela/buggy-python` is "
        "procedural (empty class diagram, honestly); this class-bearing secondary target demonstrates "
        "the OOP-extraction the §5.2 rubric asks for. The assignment permits integrating several "
        "repositories.",
        "",
        "## Summary",
        "",
        f"- Classes extracted: **{len(schema['classes'])}**",
        f"- Inheritance edges (`<|--`): **{kinds.get('inheritance', 0)}**",
        f"- Composition edges (`*--`): **{kinds.get('composition', 0)}**",
        "",
        "Representative inheritance hierarchies (verified in the extracted relations):",
        *_hierarchies(schema["relations"]),
        "",
        "## Class Diagram (full, auto-extracted)",
        "",
        schema["diagram"],
        "",
    ]
    OUT.write_text("\n".join(doc) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(schema['classes'])} classes, {kinds.get('inheritance', 0)} inheritance, "
          f"{kinds.get('composition', 0)} composition)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
